//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allert
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<bool> isRead { get; set; }
        public string Header { get; set; }
    }
}
