//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.MonitoringEvents = new HashSet<MonitoringEvent>();
        }
    
        public int DeviceID { get; set; }
        public string DeviceIP { get; set; }
        public string DeviceName { get; set; }
        public int DeviceGroup { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public string DeviceCommunity { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual DeviceType DeviceType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoringEvent> MonitoringEvents { get; set; }
    }
}
