//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OID
    {
        public int ID { get; set; }
        public int DeviceType { get; set; }
        public string Name { get; set; }
        public string OID1 { get; set; }
        public string ValueType { get; set; }
        public string Commentary { get; set; }
        public string Measure { get; set; }
    
        public virtual DeviceType DeviceType1 { get; set; }
    }
}
